// Vidéos de démo — alignées sur les athlètes (catégories cohérentes)

import type { FencingAgeCategory } from "@/lib/fencing-age-category"

export interface DemoVideo {
  id: string
  title: string
  thumbnail: string
  duration: string
  views: number
  comments: number
  athlete: string
  uploader: string
  uploadedAt: string
  weapon_type?: string
  competition_name?: string
  competition_date?: string
  category?: string
  age?: number
  /** M13 ou M15 — affiché à l'évaluateur fédéral en aveugle */
  ageCategory: FencingAgeCategory
  club?: string
  department?: string
  region?: string
}

export const DEMO_VIDEOS: DemoVideo[] = [
  {
    id: "1",
    title: "Théo Renaud — Open Nouvelle-Aquitaine M13 sabre",
    thumbnail: "https://placehold.co/400x225?text=Theo+Renaud",
    duration: "05:32",
    views: 428,
    comments: 12,
    athlete: "Théo Renaud",
    uploader: "Contact Local",
    uploadedAt: "il y a 2 jours",
    weapon_type: "sabre",
    competition_name: "Open régional",
    competition_date: "2026-01-13",
    category: "M13",
    age: 13,
    ageCategory: "M13",
    club: "Cercle d'Escrime de Bordeaux",
    department: "33",
    region: "Nouvelle-Aquitaine",
  },
  {
    id: "2",
    title: "Inès Benali — SCUF Paris, demi-finale M13",
    thumbnail: "https://placehold.co/400x225?text=Ines+Benali",
    duration: "04:18",
    views: 612,
    comments: 18,
    athlete: "Inès Benali",
    uploader: "Contact Local",
    uploadedAt: "il y a 3 jours",
    weapon_type: "sabre",
    competition_name: "Île-de-France M13",
    competition_date: "2026-01-12",
    category: "M13",
    age: 14,
    ageCategory: "M13",
    club: "SCUF Paris",
    department: "75",
    region: "Île-de-France",
  },
  {
    id: "3",
    title: "Nathan Lefèvre — Coupe cadets sabre",
    thumbnail: "https://placehold.co/400x225?text=Nathan+Lefevre",
    duration: "06:45",
    views: 890,
    comments: 22,
    athlete: "Nathan Lefèvre",
    uploader: "Coach Principal",
    uploadedAt: "il y a 4 jours",
    weapon_type: "sabre",
    competition_name: "Coupe de France cadets",
    competition_date: "2026-01-11",
    category: "M17",
    age: 15,
    ageCategory: "M17",
    club: "AS Escrime Toulouse",
    department: "31",
    region: "Occitanie",
  },
  {
    id: "4",
    title: "Chloé Marchand — Championnat PACA M15",
    thumbnail: "https://placehold.co/400x225?text=Chloe+Marchand",
    duration: "05:12",
    views: 356,
    comments: 9,
    athlete: "Chloé Marchand",
    uploader: "Contact Local",
    uploadedAt: "il y a 5 jours",
    weapon_type: "sabre",
    competition_name: "Championnat régional PACA",
    competition_date: "2026-01-10",
    category: "M17",
    age: 15,
    ageCategory: "M17",
    club: "Cercle d'Escrime Aix-en-Provence",
    department: "13",
    region: "Provence-Alpes-Côte d'Azur",
  },
  {
    id: "5",
    title: "Louis Giraud — Tournoi Grand Est M13",
    thumbnail: "https://placehold.co/400x225?text=Louis+Giraud",
    duration: "04:56",
    views: 245,
    comments: 6,
    athlete: "Louis Giraud",
    uploader: "Contact Local",
    uploadedAt: "il y a 6 jours",
    weapon_type: "sabre",
    competition_name: "Tournoi Grand Est",
    competition_date: "2026-01-09",
    category: "M13",
    age: 13,
    ageCategory: "M13",
    club: "Cercle d'Escrime Strasbourg",
    department: "67",
    region: "Grand Est",
  },
  {
    id: "6",
    title: "Sarah Okonkwo — Lyon, finale M15 sabre",
    thumbnail: "https://placehold.co/400x225?text=Sarah+Okonkwo",
    duration: "07:23",
    views: 1120,
    comments: 31,
    athlete: "Sarah Okonkwo",
    uploader: "Coach Principal",
    uploadedAt: "il y a 1 semaine",
    weapon_type: "sabre",
    competition_name: "Championnat Auvergne-Rhône-Alpes",
    competition_date: "2026-01-08",
    category: "M20",
    age: 16,
    ageCategory: "M20",
    club: "AS Escrime Lyon",
    department: "69",
    region: "Auvergne-Rhône-Alpes",
  },
  {
    id: "7",
    title: "Hugo Martel — match amical M13",
    thumbnail: "https://placehold.co/400x225?text=Hugo+Martel",
    duration: "08:15",
    views: 198,
    comments: 4,
    athlete: "Hugo Martel",
    uploader: "Contact Local",
    uploadedAt: "il y a 1 semaine",
    weapon_type: "sabre",
    competition_name: "Match amical",
    competition_date: "2026-01-07",
    category: "M13",
    age: 12,
    ageCategory: "M13",
    club: "Rennes Université Club Escrime",
    department: "35",
    region: "Bretagne",
  },
  {
    id: "8",
    title: "Élisa Fontaine — entraînement technique M15",
    thumbnail: "https://placehold.co/400x225?text=Elisa+Fontaine",
    duration: "12:34",
    views: 412,
    comments: 11,
    athlete: "Élisa Fontaine",
    uploader: "Coach Principal",
    uploadedAt: "il y a 2 semaines",
    weapon_type: "sabre",
    competition_name: "Entraînement",
    competition_date: "2026-01-05",
    category: "M17",
    age: 15,
    ageCategory: "M17",
    club: "Caen Escrime",
    department: "14",
    region: "Normandie",
  },
]
