// Données de démo — Sabre Talent (M13 / M15, sabre)

export interface DemoAthlete {
  id: string
  first_name: string
  last_name: string
  date_of_birth: string
  gender: "male" | "female"
  weapon: "foil" | "sabre" | "epee" | "épée"
  /** Catégorie projet Sabre Talent */
  age_category: "M13" | "M15"
  skill_level: "beginner" | "intermediate" | "advanced" | "elite"
  avatar_url?: string
  videos_count: number
  region: string
  club: string
  coach?: string
  ranking?: string
  recent_activity?: string
}

export const DEMO_ATHLETES: DemoAthlete[] = [
  {
    id: "1",
    first_name: "Théo",
    last_name: "Renaud",
    date_of_birth: "2012-04-18",
    gender: "male",
    weapon: "sabre",
    age_category: "M13",
    skill_level: "advanced",
    avatar_url: "https://placehold.co/200x200?text=TR",
    videos_count: 6,
    region: "Nouvelle-Aquitaine",
    club: "Cercle d'Escrime de Bordeaux",
    coach: "Marc Delaunay",
    ranking: "Top 8 régional M13 sabre",
    recent_activity: "Open régional Nouvelle-Aquitaine",
  },
  {
    id: "2",
    first_name: "Inès",
    last_name: "Benali",
    date_of_birth: "2011-09-02",
    gender: "female",
    weapon: "sabre",
    age_category: "M13",
    skill_level: "elite",
    avatar_url: "https://placehold.co/200x200?text=IB",
    videos_count: 9,
    region: "Île-de-France",
    club: "SCUF Paris",
    coach: "Claire Fontaine",
    ranking: "Top 5 national M13 sabre",
    recent_activity: "Stage national détection",
  },
  {
    id: "3",
    first_name: "Nathan",
    last_name: "Lefèvre",
    date_of_birth: "2010-11-20",
    gender: "male",
    weapon: "sabre",
    age_category: "M15",
    skill_level: "advanced",
    avatar_url: "https://placehold.co/200x200?text=NL",
    videos_count: 11,
    region: "Occitanie",
    club: "AS Escrime Toulouse",
    coach: "Julien Caron",
    ranking: "Top 12 M15 sabre",
    recent_activity: "Coupe de France cadets",
  },
  {
    id: "4",
    first_name: "Chloé",
    last_name: "Marchand",
    date_of_birth: "2010-03-07",
    gender: "female",
    weapon: "sabre",
    age_category: "M15",
    skill_level: "intermediate",
    avatar_url: "https://placehold.co/200x200?text=CM",
    videos_count: 5,
    region: "Provence-Alpes-Côte d'Azur",
    club: "Cercle d'Escrime Aix-en-Provence",
    coach: "Élodie Perrin",
    ranking: "Top 20 régional",
    recent_activity: "Championnat régional PACA",
  },
  {
    id: "5",
    first_name: "Louis",
    last_name: "Giraud",
    date_of_birth: "2012-01-14",
    gender: "male",
    weapon: "sabre",
    age_category: "M13",
    skill_level: "intermediate",
    avatar_url: "https://placehold.co/200x200?text=LG",
    videos_count: 4,
    region: "Grand Est",
    club: "Cercle d'Escrime Strasbourg",
    coach: "Thomas Klein",
    ranking: "—",
    recent_activity: "Tournoi départemental",
  },
  {
    id: "6",
    first_name: "Sarah",
    last_name: "Okonkwo",
    date_of_birth: "2009-07-30",
    gender: "female",
    weapon: "sabre",
    age_category: "M15",
    skill_level: "elite",
    avatar_url: "https://placehold.co/200x200?text=SO",
    videos_count: 14,
    region: "Auvergne-Rhône-Alpes",
    club: "AS Escrime Lyon",
    coach: "Amélie Rousseau",
    ranking: "Top 3 national M15 sabre",
    recent_activity: "Championnat de France cadets",
  },
  {
    id: "7",
    first_name: "Hugo",
    last_name: "Martel",
    date_of_birth: "2012-12-05",
    gender: "male",
    weapon: "sabre",
    age_category: "M13",
    skill_level: "beginner",
    avatar_url: "https://placehold.co/200x200?text=HM",
    videos_count: 2,
    region: "Bretagne",
    club: "Rennes Université Club Escrime",
    coach: "François Le Gall",
    ranking: "—",
    recent_activity: "Entraînement club",
  },
  {
    id: "8",
    first_name: "Élisa",
    last_name: "Fontaine",
    date_of_birth: "2010-05-22",
    gender: "female",
    weapon: "sabre",
    age_category: "M15",
    skill_level: "advanced",
    avatar_url: "https://placehold.co/200x200?text=EF",
    videos_count: 8,
    region: "Normandie",
    club: "Caen Escrime",
    coach: "Nicolas Brière",
    ranking: "Top 15 régional",
    recent_activity: "Inter-comités",
  },
  {
    id: "9",
    first_name: "Gabriel",
    last_name: "Santos",
    date_of_birth: "2011-02-11",
    gender: "male",
    weapon: "sabre",
    age_category: "M13",
    skill_level: "advanced",
    avatar_url: "https://placehold.co/200x200?text=GS",
    videos_count: 7,
    region: "Hauts-de-France",
    club: "Club Escrime Lille Métropole",
    coach: "David Leroy",
    ranking: "Top 10 régional",
    recent_activity: "Open Hauts-de-France",
  },
  {
    id: "10",
    first_name: "Maëlys",
    last_name: "Dufour",
    date_of_birth: "2012-08-19",
    gender: "female",
    weapon: "sabre",
    age_category: "M13",
    skill_level: "intermediate",
    avatar_url: "https://placehold.co/200x200?text=MD",
    videos_count: 5,
    region: "Pays de la Loire",
    club: "Nantes Métropole Escrime",
    coach: "Laura Pichon",
    ranking: "—",
    recent_activity: "Critérium jeunes",
  },
  {
    id: "11",
    first_name: "Adam",
    last_name: "Kowalski",
    date_of_birth: "2009-10-03",
    gender: "male",
    weapon: "sabre",
    age_category: "M15",
    skill_level: "advanced",
    avatar_url: "https://placehold.co/200x200?text=AK",
    videos_count: 10,
    region: "Centre-Val de Loire",
    club: "Orléans Escrime",
    coach: "Vincent Morel",
    ranking: "Top 8 régional",
    recent_activity: "Tournoi national junior",
  },
  {
    id: "12",
    first_name: "Léna",
    last_name: "Haddad",
    date_of_birth: "2010-01-28",
    gender: "female",
    weapon: "sabre",
    age_category: "M15",
    skill_level: "elite",
    avatar_url: "https://placehold.co/200x200?text=LH",
    videos_count: 12,
    region: "Corse",
    club: "Bastia Escrime",
    coach: "Jean-Paul Santini",
    ranking: "Top 6 national M15 sabre",
    recent_activity: "Stage national Toussaint",
  },
]
